- name: Info message
  ansible.builtin.debug:
    msg: "Using static binary install"

- name: Create tenzir group
  ansible.builtin.group:
    name: tenzir
    state: present

- name: Create tenzir user
  ansible.builtin.user:
    name: tenzir
    groups: tenzir
    shell: /sbin/nologin
    append: yes
    state: present
    create_home: no

- name: Copy service definition file
  ansible.builtin.copy:
    src: tenzir.service
    dest: /etc/systemd/system
    mode: preserve
    owner: root
    group: root

- name: Copy the tarball to the target host
  ansible.builtin.copy:
    src: "{{ tenzir_archive }}"
    dest: /tmp/tenzir.tar.gz
    mode: '0640'
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  register: tenzir_download

- name: Create /var/lib/tenzir
  ansible.builtin.file:
    path: "/var/lib/tenzir"
    state: directory
    mode: '0755'
    owner: tenzir
    group: tenzir

- name: Create /var/log/tenzir
  ansible.builtin.file:
    path: "/var/log/tenzir"
    state: directory
    mode: '0755'
    owner: tenzir
    group: tenzir

- name: Unarchive Tenzir release tarball
  ansible.builtin.unarchive:
    src: "/tmp/tenzir.tar.gz"
    dest: /
    remote_src: yes
