[build-system]
requires = ["uv_build>=0.8.14,<0.10.0"]
build-backend = "uv_build"

[project]
name = "tenzir-operator"
version = "5.23.1"
description = "Tenzir Python operator runtime"
requires-python = ">=3.9"
license = "BSD-3-Clause"
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
  { name = "Tenzir", email = "engineering@tenzir.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
]
# Align wheels generation in /python/default.nix when you add exclusive
# dependencies to tenzir-operator. In case a dependency relies on compiled code,
# add it as a dependency to the `tenzir` siblingproject as well instead.
dependencies = [
  "python-box>=7.0",
  "tenzir-common>=5.23.1,<5.24.0",
]

[tool.uv.sources]
tenzir-common = { workspace = true }
