version: "3"
services:
  vast:
    # TODO: Consider switching from latest to stable by default, which offers a
    # better user experience. We can only do this after the release of VAST v2.4
    # at the earliest, which will be the first release to offer a stable tag for
    # Docker Hub.
    image: ${VAST_CONTAINER_REGISTRY:-docker.io}/tenzir/tenzir:${VAST_CONTAINER_REF:-latest}
    container_name: ${VAST_CONTAINER_NAME:-vast-server}
    environment:
      - TENZIR_ENDPOINT=vast:5158
      - TENZIR_START__COMMANDS=web server
      - TENZIR_PLUGINS__WEB__MODE=dev
      - TENZIR_PLUGINS__WEB__BIND=0.0.0.0
      - TENZIR_PLUGINS__WEB__PORT=5160
    ports:
      - ${VAST_WEB_PORT:-5160}:5160
      - ${VAST_PORT:-5158}:5158
    command:
      - start
    networks:
      - vast

networks:
  vast:
    driver: bridge
