name: Labels
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  check-labels:
    name: Check Labels
    runs-on: ubuntu-latest
    steps:
      - name: No Labels
        run: |
          # Fail if the PR has no labels.
          echo '${{ toJson(github.event.pull_request.labels.*.name) }}' |
            jq -re 'length > 0'
      - name: Blocked
        run: |
          # Fail if the PR has the 'blocked' label.
          echo '${{ toJson(github.event.pull_request.labels.*.name) }}' |
            jq -re 'all(. != "blocked")'
