name: Code Intelligence Fuzzing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  FUZZING_SERVER_ADDRESS: 'localhost:443'
  WEB_APP_ADDRESS:  'http://localhost:6775'
  VAST_VERSION_TAG: 2021.03.30+ci 
  

jobs:
  fuzz_parsers:
    runs-on: ubuntu-latest
    steps:
      - id: start-fuzzing
        name: Build and Instrument
        uses: CodeIntelligenceTesting/github-actions/start-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection: "projects/initial-fuzzing-c6e8b32e/campaigns/parse_query-20e3604d"
          git_reference: ${{ github.sha }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}          
      - id: monitor-fuzzing
        name: Fuzzing
        uses: CodeIntelligenceTesting/github-actions/monitor-fuzzing@v3
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ github.token }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
      - id: report-coverage
        name: Report Coverage
        uses: CodeIntelligenceTesting/github-actions/report-coverage@v3
        if: ${{ github.event_name == 'pull_request' && (success() || failure()) }}
        with:
          ci_fuzz_api_token: ${{ secrets.CI_FUZZ_API_TOKEN }}
          test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
          github_token: ${{ github.token }}
          pull_request_number: ${{ github.event.pull_request.number }}
          owner: ${{ github.event.repository.owner.login }}
          repository: ${{ github.event.repository.name }}
          git_reference: ${{ github.sha }}
          fuzzing_server_address: ${{ env.FUZZING_SERVER_ADDRESS }}
          dashboard_address: ${{ env.WEB_APP_ADDRESS }}
          
