[tool.poetry]
name = "vast-website"
version = "0.1.0"
description = "VAST website"
authors = ["Tenzir <engineering@tenzir.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.10"
nbconvert = "^6.5.3"
ipykernel = "^6.15.1"
bash_kernel = "^0.7.2"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
